### ISSUE TITLE
Copyright for reuse?

### ISSUE THREAD

**Issue by elliewix** [codeandcognition/archive-2018cse-xie#1]
Hi Team!

I recently read the associated paper that this repo supports, and am extremely keen to implement some of these exercises within my python classroom.  I've read through some of the experimental packet, and would love to adapt some of the examples. 

However, I can't find a copyright/reuse statement for the content. I would of course provide attribution, but it's otherwise unclear if you would be okay with reuse/remix or not.  I'm happy to provide suggestions and talk through some pros/cons for some of the licenses/declarations available.  

Let me know!

**Comment by bxie** [comment]
Hi Ellie,

Thanks for reaching out! We'd be thrilled if you adapted and experimented with these examples. I added a [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license. Let me know if I can answer additional questions and please let me know what you discover!

-Benji
bxie{at]uw.edu
